development:
    dialect: mysql
    datasource: root:${DB_PASSWORD}@tcp(0.0.0.0:3306)/root?charset=utf8mb4&parseTime=True
    dir: db/migrations
    table: migrations

production:
    dialect: mysql
    datasource: ${DB_USER}:${DB_PASSWORD}@tcp(${DB_HOST}:3306)/${DB_NAME}?charset=utf8mb4&parseTime=True
    dir: db/migrations
    table: migrations